[package]
name = "cell_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15"
ndarray-npy = "0.7"
plotters = "0.3"
image = "0.23"
gif = "0.11"
regex = "1"
itertools = "0.10"
